### ISSUE TITLE
Wrong mkdocs installation destination

### ISSUE THREAD

**Issue by sleinen** [rare-freertr/RARE-web#5]
The `mkdocs.yml` points to a neighboring directory as the installation target:

```
site_dir: ../frederic-loui.github.io/
```

Shouldn't this point to `../docs.freertr.org` instead?

**Comment by frederic-loui** [comment]
Thanks for spotting this issue. As per gitHub rule, it should point to `rare-freertr.github.io` I'll test with `docs.freertr.org`
